name: "Submodule versions and release metadata"
description: "Collect submodule versions and generate release metadata JSON"
author: "Your Name"

inputs:
  output-file:
    description: "Name of the generated release JSON file"
    required: false
    default: "release.json"
  ext-versions:
    description: "File containing additonal firmware releases not covered by submodules"
    required: false

runs:
  using: "composite"
  steps:
    - name: Generate submodule_versions.txt
      shell: bash
      run: python3 "${GITHUB_ACTION_PATH}/collect_submodules.py"

    - name: Generate release JSON
      shell: bash
      run: python3 "${GITHUB_ACTION_PATH}/generate_json_release.py" -o "${{ inputs.output-file }}" -e "${{ inputs.ext-versions}}"

    - name: Upload submodule_versions.txt artifact
      uses: actions/upload-artifact@v4
      with:
        name: submodule-versions
        path: submodule_versions.txt

    - name: Upload release JSON artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-json
        path: ${{ inputs.output-file }}
