name: "Build Python wheel with Hatch"
description: "Builds a Python wheel with Hatch using a provided version tag and uploads the artifact."

inputs:
  tag:
    description: "Version tag to use (e.g. v1.0.0.dev5)"
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        
    - name: Export package version from computed tag
      run: |
        TAG='${{ inputs.tag }}'
        # Strip leading "v" for PEP 440 compliance, e.g. v1.2.3.dev5 -> 1.2.3.dev5
        echo "PKG_VERSION=${TAG#v}" >> "$GITHUB_ENV"

    - name: Install build dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        pip install -e .[prod]

    - name: Build wheel with Hatch
      shell: bash
      run: hatch build -t wheel

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheel-dist
        path: dist/*.whl
        if-no-files-found: error
