name: "Minimal C: Formatting"
description: "Install clang-format and check changed files"

inputs:
  base-ref:
    description: "Base ref to diff against (defaults to main if empty)"
    required: false
  changed-exts:
    description: "Comma-separated extensions"
    required: false
    default: "c,cc,cpp,h,proto"
  ignore-files:
    description: "Comma-separated list of files or glob patterns to ignore"
    required: false
    default: ""
  clang-format-version:
    description: "LLVM clang-format version"
    required: false
    default: "20.1.8"  # update as needed
  ubuntu-suffix:
    description: "Runner suffix (24.04 on ubuntu-latest today)"
    required: false
    default: "ubuntu-24.04"

runs:
  using: "composite"
  steps:
    - name: Install clang-format-20 fast (no llvm.sh, no MS repos)
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -euxo pipefail

        # If already present on the image, don't do anything
        if command -v clang-format-20 >/dev/null 2>&1; then
          clang-format-20 --version
          exit 0
        fi

        # Avoid slow man-db triggers entirely
        sudo apt-get -yq remove --purge man-db || true

        # The runner image has Microsoft repos that can time out -> remove them
        sudo rm -f /etc/apt/sources.list.d/*microsoft*.list || true
        sudo rm -f /etc/apt/sources.list.d/*azure*.list || true
        sudo sed -i '/packages\.microsoft\.com/d' /etc/apt/sources.list || true

        # Add only the LLVM 20 repo + key (NO llvm.sh; it drags in lots of stuff)
        curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key \
          | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc >/dev/null
        echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-20 main" \
          | sudo tee /etc/apt/sources.list.d/llvm20.list >/dev/null

        # Short network timeouts and minimal retries so we fail fast on any flaky mirror
        AOPTS='-o Acquire::http::Timeout=5 -o Acquire::https::Timeout=5 -o Acquire::Retries=1'

        sudo apt-get $AOPTS update -yq
        sudo apt-get $AOPTS install -yq --no-install-recommends clang-format-20

        clang-format-20 --version


    - name: Verify clang-format version
      shell: bash
      run: clang-format-20 --version

    - name: Formatting Check
      shell: bash
      run: |
        BASE_REF="${{ inputs.base-ref }}"
        python3 "${GITHUB_ACTION_PATH}/formatting_check.py" \
          --base-ref "${BASE_REF:-main}" \
          --changed-exts "${{ inputs.changed-exts }}" \
          --ignore-files "${{ inputs.ignore-files }}"
