name: "Minimal C: Formatting"
description: "Install clang-format and check changed files"

inputs:
  base-ref:
    description: "Base ref to diff against (defaults to main if empty)"
    required: false
  changed-exts:
    description: "Comma-separated extensions"
    required: false
    default: "c,cc,cpp,h,proto"
  ignore-files:
    description: "Comma-separated list of files or glob patterns to ignore"
    required: false
    default: ""
  clang-format-version:
    description: "LLVM clang-format version"
    required: false
    default: "20.1.8"  # update as needed
  ubuntu-suffix:
    description: "Runner suffix (24.04 on ubuntu-latest today)"
    required: false
    default: "ubuntu-24.04"

runs:
  using: "composite"
  steps:
    - name: Install clang-format (download release, no APT)
      shell: bash
      run: |
        set -euxo pipefail
        ver="${{ inputs.clang-format-version }}"
        suf="${{ inputs.ubuntu-suffix }}"
        url="https://github.com/llvm/llvm-project/releases/download/llvmorg-${ver}/clang+llvm-${ver}-x86_64-linux-gnu-${suf}.tar.xz"

        work="$(mktemp -d)"
        curl -L "$url" | tar -xJ -C "$work"
        # Extract just the binary to keep things tiny and fast
        binpath="$(find "$work" -type f -path "*/bin/clang-format" | head -n1)"
        sudo install -m 0755 "$binpath" /usr/local/bin/clang-format-20
        sudo ln -sf /usr/local/bin/clang-format-20 /usr/local/bin/clang-format

    - name: Verify clang-format version
      shell: bash
      run: clang-format-20 --version

    - name: Formatting Check
      shell: bash
      run: |
        BASE_REF="${{ inputs.base-ref }}"
        python3 "${GITHUB_ACTION_PATH}/formatting_check.py" \
          --base-ref "${BASE_REF:-main}" \
          --changed-exts "${{ inputs.changed-exts }}" \
          --ignore-files "${{ inputs.ignore-files }}"
