name: "Minimal C: Formatting"
description: "Install clang-format and check changed files"
inputs:
  base-ref:
    description: "Base ref to diff against (defaults to main if empty)"
    required: false
  changed-exts:
    description: "Comma-separated extensions"
    required: false
    default: "c,cc,cpp,h,proto"

runs:
  using: "composite"
  steps:
    - name: Instal clang-format-20
      shell: bash
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt-get install -y clang-format-20

    - name: Verify clang-format version
      shell: bash
      run: clang-format-20 --version

    - name: Formatting Check
      shell: bash
      run: |
        python3 "${GITHUB_ACTION_PATH}/formatting_check.py" \
          --base-ref "${{ inputs.base-ref }}" \
          --changed-exts "${{ inputs.changed-exts }}"
