name: "Publish STM32 Firmware (GitHub Release → AWS CodeArtifact)"
description: |
  Bundles STM32 firmware artifacts, uploads them to a GitHub release, and
  publishes the bundle to AWS CodeArtifact. Mirrors the behaviour of the
  Python build-deploy action: pull_request events push to the DEV repository,
  while pushes to refs/heads/main target the PROD repository.

inputs:
  tag:
    description: "Version tag to use (e.g., v1.2.3 or v1.2.3-dev4). Leading 'v' is stripped for versioning."
    required: true
  artifact-pattern:
    description: "Artifact name or glob pattern to download (actions/download-artifact pattern syntax)."
    required: true
  package-name:
    description: "CodeArtifact package name to publish."
    required: true

runs:
  using: "composite"
  steps:

    - name: Download firmware artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.artifact-pattern }}
        path: release/artifacts
        merge-multiple: true

    # Derive VERSION (strip leading v), PACKAGE and FILENAME for reuse
    - name: Derive version and filenames
      shell: bash
      run: |
        RAW="${{ inputs.tag }}"
        VERSION="${RAW#v}"
        PACKAGE="${{ inputs.package-name }}"
        FILENAME="${PACKAGE}-${VERSION}.zip"
        echo "VERSION=$VERSION"   >> "$GITHUB_ENV"
        echo "PACKAGE=$PACKAGE"   >> "$GITHUB_ENV"
        echo "FILENAME=$FILENAME" >> "$GITHUB_ENV"

    - name: Create firmware bundle (.zip)
      shell: bash
      run: |
        mkdir -p release
        (cd release && zip -r "../$FILENAME" artifacts)

    # ===== PROD path (pushes to main) =====
    - name: Configure AWS credentials (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_CODEARTIFACT_PUBLISHER }}
        aws-region:     ${{ env.AWS_REGION_CODEARTIFACT }}
        role-duration-seconds: 1800

    - name: Publish generic package to CodeArtifact (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        # Re-derive a clean semver (e.g., 0.1.7 or 0.1.7-dev4) from the tag
        RAW="${{ inputs.tag }}"
        VERSION="$(echo "$RAW" | grep -oE '[0-9]+\.[0-9]+\.[0-9]([0-9A-Za-z\.-]*)?')"
        : "${VERSION:?Could not parse version from tag: $RAW}"
        PACKAGE="${{ inputs.package-name }}"
        FILENAME="${PACKAGE}-${VERSION}.zip"

        # Hash the asset per CodeArtifact generic requirements
        ASSET_SHA256="$(sha256sum "$FILENAME" | awk '{print $1}')"

        aws codeartifact publish-package-version \
          --domain "${{ env.AWS_DOMAIN }}" \
          --domain-owner "${{ env.AWS_DOMAIN_OWNER }}" \
          --repository "${{ env.AWS_STM32_REPO_PROD }}" \
          --format generic \
          --package "$PACKAGE" \
          --package-version "$VERSION" \
          --asset-content "$FILENAME" \
          --asset-name "$FILENAME" \
          --asset-sha256 "$ASSET_SHA256"

    # ===== DEV path (PRs and non-main pushes) =====
    - name: Configure AWS credentials (DEV)
      if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main') }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_CODEARTIFACT_PUBLISHER }}
        aws-region:     ${{ env.AWS_REGION_CODEARTIFACT }}
        role-duration-seconds: 1800

    - name: Publish generic package to CodeArtifact (DEV)
      if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main') }}
      shell: bash
      run: |
        RAW="${{ inputs.tag }}"
        VERSION="$(echo "$RAW" | grep -oE '[0-9]+\.[0-9]+\.[0-9]([0-9A-Za-z\.-]*)?')"
        : "${VERSION:?Could not parse version from tag: $RAW}"
        PACKAGE="${{ inputs.package-name }}"
        FILENAME="${PACKAGE}-${VERSION}.zip"

        ASSET_SHA256="$(sha256sum "$FILENAME" | awk '{print $1}')"

        aws codeartifact publish-package-version \
          --domain "${{ env.AWS_DOMAIN }}" \
          --domain-owner "${{ env.AWS_DOMAIN_OWNER }}" \
          --repository "${{ env.AWS_STM32_REPO_DEV }}" \
          --format generic \
          --package "$PACKAGE" \
          --package-version "$VERSION" \
          --asset-content "$FILENAME" \
          --asset-name "$FILENAME" \
          --asset-sha256 "$ASSET_SHA256"
