name: "Publish STM32 Firmware (GitHub Release → AWS CodeArtifact)"
description: |
  Bundles STM32 firmware artifacts, uploads them to a GitHub release, and
  publishes the bundle to AWS CodeArtifact. Mirrors the behaviour of the
  Python build-deploy action: pull_request events push to the DEV repository,
  while pushes to refs/heads/main target the PROD repository.

inputs:
  tag:
    description: "Version tag to use (e.g., BCU_BL_v1.2.3 or v1.2.3-rc1). A clean semver is extracted for publishing."
    required: true
  artifact-pattern:
    description: "Artifact name or glob pattern to download (actions/download-artifact pattern syntax)."
    required: true
  package-name:
    description: "CodeArtifact package name to publish."
    required: true
  namespace:
    description: "CodeArtifact namespace for the generic package (required by generic format, e.g., 'bcu')."
    required: true
  github_token:
    description: "Token for 'gh' to call releases/generate-notes (usually GITHUB_TOKEN)."
    required: true

runs:
  using: "composite"
  steps:
    - name: Download firmware artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.artifact-pattern }}
        path: release/artifacts
        merge-multiple: true

    - name: Derive version and filenames
      shell: bash
      run: |
        set -euo pipefail
        python "${GITHUB_ACTION_PATH}/scripts/derive_metadata.py" "${{ inputs.tag }}" "${{ inputs['package-name'] }}" "${{ inputs.namespace }}"

    - name: Create firmware bundle (.zip)
      shell: bash
      run: |
        set -euo pipefail
        python "${GITHUB_ACTION_PATH}/scripts/create_firmware_bundle.py"

    - name: Check PAT availability (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        set -euo pipefail
        python "${GITHUB_ACTION_PATH}/scripts/check_pat.py"

    # ====================== PROD path (pushes to main) ======================
    - name: Configure AWS credentials (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_CODEARTIFACT_PUBLISHER }}
        aws-region:     ${{ env.AWS_REGION_CODEARTIFACT }}
        role-duration-seconds: 1800

    - name: Publish generic package to CodeArtifact (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        set -euo pipefail
        python "${GITHUB_ACTION_PATH}/scripts/publish_codeartifact.py" --repository "${{ env.AWS_STM32_REPO_PROD }}"

    - name: Extract PR summary for release body (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      id: release-body
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail
        python "${GITHUB_ACTION_PATH}/scripts/extract_release_body_from_pr.py" --tag "${{ inputs.tag }}"
        
    - name: Print release notes
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      shell: bash
      run: |
        echo "===== RELEASE NOTES BEGIN ====="
        printf "%s\n" "${{ steps.release-body.outputs.body }}"
        echo "===== RELEASE NOTES END ====="

    - name: Create/Update GitHub Release (PROD)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ env.PACKAGE }} ${{ env.VERSION }}
        draft: false
        prerelease: false
        # We now fully control the body; no auto-generated notes.
        body: ${{ steps.release-body.outputs.body }}
        files: ${{ env.FILENAME }}
        token: ${{ env.GITHUB_ACTIONS_BOT }}

    # ================== DEV path (PRs and non-main pushes) ==================
    - name: Configure AWS credentials (DEV)
      if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main') }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_CODEARTIFACT_PUBLISHER }}
        aws-region:     ${{ env.AWS_REGION_CODEARTIFACT }}
        role-duration-seconds: 1800

    - name: Publish generic package to CodeArtifact (DEV)
      if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref != 'refs/heads/main') }}
      shell: bash
      run: |
        set -euo pipefail
        python "${GITHUB_ACTION_PATH}/scripts/publish_codeartifact.py" --repository "${{ env.AWS_STM32_REPO_DEV }}"
