#action.yml
name: 'STM32CubeIDE Build (composite)'
description: 'Checkout (submodules), fetch version.h, run Docker build, upload artifacts'
inputs:
  version-art-name:
    description: 'Artifact name that contains version.h'
    required: true
  version-location:
    description: 'Where to place version.h (e.g., main-app/Core/Inc)'
    required: true
  project-path:
    description: 'Path to STM32CubeIDE project (e.g., main-app or bootloader)'
    required: true
  project-target:
    description: 'STM32CubeIDE target in the form target/[build-configuration]'
    required: true
  fw_art_name:
    description: 'Name for the uploaded firmware artifact (can include expressions)'
    required: true
  checkout-token:
    description: 'Token for submodule checkout (defaults to runner token if not provided)'
    required: false
runs:
  using: 'composite'
  steps:

    - name: Download generated version.h
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.version-art-name }}
        path: ${{ inputs.version-location }}

    # Build + run the Docker image that contains STM32CubeIDE
    # Assumes a Dockerfile lives in the same action folder (this directory).
    - name: Build tool image
      shell: bash
      run: |
        docker build -t stm32cubeide-builder "${GITHUB_ACTION_PATH}"

    - name: Build firmware
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
        PROJECT_TARGET: ${{ inputs.project-target }}
      run: |
        # Mount workspace; pass args expected by your Docker entrypoint
        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/workspace" \
          -w /workspace \
          stm32cubeide-builder \
          "${PROJECT_PATH}" "${PROJECT_TARGET}"

    - name: Derive build configuration
      id: derive-build-config
      shell: bash
      run: |
        project_target="${{ inputs.project-target }}"
        build_config="${project_target##*/}"
        echo "build_configuration=$build_config" >> "$GITHUB_OUTPUT"
        echo "BUILD_CONFIGURATION=$build_config" >> "$GITHUB_ENV"

    # Upload artifacts produced for the derived build configuration.
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.fw_art_name }}
        path: |
          ${{ inputs.project-path }}/${{ steps.derive-build-config.outputs.build_configuration }}/*.elf
          ${{ inputs.project-path }}/${{ steps.derive-build-config.outputs.build_configuration }}/*.bin
          ${{ inputs.project-path }}/${{ steps.derive-build-config.outputs.build_configuration }}/*.hex
